### ISSUE TITLE
CLI error when installing via npx

### ISSUE THREAD

**Issue by danilosilvadev** [akallidreams/create-akalli-app#1]
```
sudo npx @akalli/create-akalli-app my-app-beuty
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/32203/lib/node_modules/@akalli/create-akalli-app/node_modules/styled-components/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! styled-components@5.3.5 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the styled-components@5.3.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-11T13_56_27_771Z-debug.log
Install for @akalli/create-akalli-app@latest failed with code 1
```

For now i will use git clone as main way to install project.

Related files:

[./bin/akalli-cli.js](https://github.com/akallidreams/create-akalli-app/blob/master/bin/akalli-cli.js)

**Comment by danilosilvadev** [comment]
Fixed by deleting react-native async storage community version
